### ISSUE TITLE
How to filter data by mobile app?

### ISSUE THREAD

**Issue by keshk26** [neiker/analytics-react-native#127]
I am trying to use this library for my RN project. I set up the source in Segment as a **website**. I then made destinations to Google Analytics and Mixpanel. We also have a website sending events the same way via Segment. We have one QA project each for GA and Mixpanel. 

At the moment, the RN events are showing up in Mixpanel as browser data. Is there a way to filter out the website/app data in a single Mixpanel/GA project? If there is no elegant option, I am guessing we would have to make different projects for app data in Mixpanel and GA.    

Thanks for any help!

**Comment by neiker** [comment]
Hi @keshk26, sorry for the delay.

I don't have this problem because we never had to filter by source, but I think the problem is here: 
https://github.com/neiker/analytics-react-native/blob/master/src/index.js#L256
I think as `analytics-react-native` is not a valid source for segment, they fall to the default wich is web. If this is true, can be solved changing `analytics-react-native` to be `analytics-ios` or `analytics-android` depending on the device.

Feel free to send a pull request if this work to you.

**Comment by neiker** [comment]
More info here: https://community.segment.com/r/18z1hd

**Comment by neiker** [comment]
Solved on [v1.2.0](https://github.com/neiker/analytics-react-native/releases/tag/v1.2.0)

**Comment by leethree** [comment]
I think the type of Segment source is decided by what you selected in the "Sources Catalog". We selected "Node.js Server" when integrating `analytics-react-native` so the source is considered a "server". Changing the `context.library.name` value probably doesn't make a difference here.
